# Generated by Django 3.1.1 on 2021-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210104_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondiscount',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
